# Generated by Django 4.0.3 on 2022-04-29 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Название')),
                ('media', models.FileField(blank=True, null=True, upload_to='', verbose_name='Аудиозапись')),
                ('date', models.DateTimeField(verbose_name='Дата публикации')),
            ],
        ),
    ]
