# Generated by Django 4.0.4 on 2022-05-06 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_articles_options_alter_articles_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='date',
            field=models.DateTimeField(blank=True, verbose_name='Дата публикации'),
        ),
    ]
