# Generated by Django 4.0.4 on 2022-05-07 12:19

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_articles_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='date',
            field=models.DateTimeField(verbose_name='Дата публикации'),
        ),
    ]
