# Generated by Django 4.0.4 on 2022-05-07 16:19

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_remove_articles_content_articles_content_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='Редактор'),
        ),
    ]
