# Generated by Django 4.0.4 on 2022-05-07 18:49

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_alter_articles_content_alter_articles_content_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Редактированный текст'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='media', verbose_name='Аудиозапись'),
        ),
    ]
