# Generated by Django 4.0.4 on 2022-05-07 18:50

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_alter_articles_content_alter_articles_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Редактированный текст'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='media',
            field=models.FileField(upload_to='media', verbose_name='Аудиозапись'),
        ),
    ]
