# Generated by Django 4.0.4 on 2022-05-07 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_alter_articles_content_alter_articles_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='content',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='content_file',
        ),
    ]
