# Generated by Django 4.0.4 on 2022-05-08 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_remove_articles_content_remove_articles_content_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='content_url',
            field=models.URLField(blank=True, default='', verbose_name='Ссылка на текстовый документ'),
        ),
    ]
